name: Frontend Security Analysis Reports

on:
  push:
    branches: [ main, 'feature/*' ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * 0'  # Run weekly on Sundays

jobs:
  security-reports:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci
        continue-on-error: true

      - name: Run ESLint
        run: |
          npm run lint -- -f json -o eslint_report.json || true
        continue-on-error: true

      - name: Run npm audit SAST
        run: |
          npm audit --json > npm_audit_SAST_report.json 2>&1 || true
          if [ ! -f npm_audit_SAST_report.json ]; then
            echo '{"error": "No vulnerabilities found"}' > npm_audit_SAST_report.json
          fi
        continue-on-error: true

      - name: Start frontend application
        run: |
          npm run dev &
          sleep 20  # Increased sleep time to ensure dev server is ready
        continue-on-error: true

      - name: ZAP Scan
        uses: zaproxy/action-full-scan@v0.11.0
        with:
          target: 'http://localhost:3000'
          token: ${{ secrets.GITHUB_TOKEN }}
          cmd_options: '-t http://localhost:3000 -r zap_report.html'
        continue-on-error: true

      - name: Verify reports
        run: |
          ls -la eslint_report.json
          ls -la npm_audit_SAST_report.json
          ls -la zap_report.html
        continue-on-error: true

      - name: Upload security reports
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: security-reports
          path: |
            zap_report.html
            eslint_report.json
            npm_audit_SAST_report.json
